# Generated by Django 3.0.3 on 2020-02-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('event', models.ManyToManyField(to='users.Event')),
            ],
        ),
    ]
